site_name: My Docs
site_name: Oferta Academica UTPL
site_url: https://universidad-utpl-actividades.github.io/malla-curricular-Actividad/



nav:
  - Inicio: index.md
  - Ciencias Administrativas: administrativa.md
  - Ciencias Sociales: sociales.md
  - Ciencias Exactas: exactas.md
  - Ciencias de la Salud: salud.md
  - Ciencias Economicas y sociales: ciencias economicas y empresariales.md