site_name: My Docs
site_name: Oferta Academica UTPL
site_url: https://universidad-sergi.github.io/oferta

theme:
  name: readthedocs  # Este tema es mucho más simple y menos "pro" que el anterior

nav:
  - Inicio: index.md
  - Ciencias Administrativas: administrativa.md
  - Ciencias Sociales: sociales.md
  - Ciencias Exactas: exactas.md
  - Ciencias de la Salud: salud.md